export const Produtos = [

  {
    id: 1,
    nome: "Camiseta Avenger",
    desc: "Tamanhos P PP M G",
    preco: 25.90,
    foto: "../assets/img/cami1.png",
    desconto: 0,
    pontosDasAvaliacoes: 4,
    totalDeAvaliacoes: 350,
    disponibilidade: 5,
    totalDeCompras: 0,
    peso: 160,
    ehVegetariano: false,
    categosriaId: 1,

  },
  {
    id: 2,
    nome: "Camiseta Marvel",
    desc: "Tamanhos P PP M G",
    preco: 26.90,
    foto: "../assets/img/cami2.png",
    desconto: 5,
    pontosDasAvaliacoes: 4,
    totalDeAvaliacoes: 350,
    disponibilidade: 10,
    totalDeCompras: 0,
    peso: 190,
    ehVegetariano: true,
    categosriaId: 2,

  },
  {
    id: 3,
    nome: "Camiseta DC",
    desc: "Tamanhos P PP M G",
    preco: 29.90,
    foto: "../assets/img/cami3.png",
    desconto: 25,
    pontosDasAvaliacoes: 5,
    totalDeAvaliacoes: 390,
    disponibilidade: 1,
    totalDeCompras: 0,
    peso: 190,
    ehVegetariano: false,
    categosriaId: 3,

  },
  {
    id: 4,
    nome: "Camiseta DC",
    desc: "Tamanhos P PP M G",
    preco: 29.90,
    foto: "../assets/img/cami4.png",
    desconto: 25,
    pontosDasAvaliacoes: 5,
    totalDeAvaliacoes: 390,
    disponibilidade: 1,
    totalDeCompras: 0,
    peso: 190,
    ehVegetariano: false,
    categosriaId: 4,

  },
  {
    id: 5,
    nome: "Camiseta DC",
    desc: "Tamanhos P PP M G",
    preco: 29.90,
    foto: "../assets/img/cami5.png",
    desconto: 25,
    pontosDasAvaliacoes: 56,
    totalDeAvaliacoes: 390,
    disponibilidade: 23,
    totalDeCompras: 0,
    peso: 190,
    ehVegetariano: false,
    categosriaId: 5,

  },
  {
    id: 6,
    nome: "Camiseta Haaaaa",
    desc: "Tamanhos P PP M G",
    preco: 29.90,
    foto: "../assets/img/cami6.png",
    desconto: 25,
    pontosDasAvaliacoes: 5,
    totalDeAvaliacoes: 390,
    disponibilidade: 1,
    totalDeCompras: 0,
    peso: 190,
    ehVegetariano: false,
    categosriaId: 6,

  },
  {
    id: 7,
    nome: "Camiseta DC",
    desc: "Tamanhos P PP M G",
    preco: 29.90,
    foto: "../assets/img/cami7.png",
    desconto: 2,
    pontosDasAvaliacoes: 5,
    totalDeAvaliacoes: 390,
    disponibilidade: 1,
    totalDeCompras: 0,
    peso: 190,
    ehVegetariano: false,
    categosriaId: 7,

  },

]
